source:      .
destination: ./_site
includes:    ./_includes
baseurl: 

collections:
  projects:
    output: true
    
# Other options
#permalink: blog/:year/:month/:title
excerpt_separator: <!--more-->

title: julia-di.com
description: Julia Di
google_analytics: 
show_downloads: true
theme: 
