source:      .
destination: ./_site
includes:    ./_includes
baseurl: /~juliadi

collections:
  projects:
    output: true
    
# Other options
#permalink: blog/:year/:month/:title
excerpt_separator: <!--more-->
